### ISSUE TITLE
Clash 订阅链接中存在 shadow-tls 类型节点时，导入错误

### ISSUE THREAD

**Issue by ghost** [rnetx/sing-box#40]
### Operating system

Linux

### System version

linux 6.5.8-1

### Installation type

Original sing-box Command Line

### Version

<details>

```console
sing-box version unknown

Environment: go1.21.3 linux/amd64
Tags: with_quic,with_grpc,with_wireguard,with_ech,with_utls,with_reality_server,with_clash_api,with_gvisor,with_proxyprovider
Revision: 0dee5758ec57e8fd93e9225d90397c186826c5d9
CGO: enabled
```
</details>

### Description

尝试在 proxyprovider 中导入包含 shadow-tls 类型节点的 Clash 订阅链接时，会出现错误提示：
```console
FATAL[0000] create service: get outbounds from proxyprovider[0]: update outbounds failed: parse config failed, config is not clash config or raw links or sing-box config
```
使用命令 `./sing-box parselink -l "订阅链接"` 进行测试同样提示 `parse config failed, config is not clash config or raw links or sing-box config`。

订阅链接中的内容示例：
```yaml
proxies:
  - name: "ss4-shadow-tls"
    type: ss
    server: server
    port: 443
    cipher: 2022-blake3-aes-128-gcm
    password: "password"
    plugin: shadow-tls
    client-fingerprint: chrome
    plugin-opts:
      host: "example.com"
      password: "shadow_tls_password"
      version: 2 # support 1/2/3
```

### Reproduction

1. 获取一个包含 shadow-tls 类型节点的 Clash 订阅链接。
2. 使用命令 `./sing-box parselink -l "订阅链接"` 进行测试。
